### ISSUE TITLE
Svelte JS Support

### ISSUE THREAD

**Issue by rinkusam12** [szymmis/vite-express#10]
Would be nice to add svelte js support

**Comment by szymmis** [comment]
Hi @rinkusam12. `vite-express` is supposed to be framework agnostic and as long as Vite is supporting it, it should work with this package. There isn't a template available in `create-vite-express` package but you can scaffold your app with `create-vite` and then add express server as described in the second part of [:package: Installation & usage](https://github.com/szymmis/vite-express#-installation--usage) README section. Of course adding Svelte to `create-vite-express` would be great and I'll definitely have that in mind! Thanks for you input. If you have any questions about the setup, feel free to ask!
