### ISSUE TITLE
TypeScript error: Relative import paths need explicit file extensions in ECMAScript imports

### ISSUE THREAD

**Issue by borzaka** [szymmis/vite-express#104]
In: `src/client/main.tsx`:
https://github.com/szymmis/vite-express/blob/1189de884ea240bb95c60b1db4a516c381b301f2/create-vite-express/templates/react-ts/src/client/main.tsx#L6

> TS2835: Relative import paths need explicit file extensions in ECMAScript imports when --moduleResolution is node16 or nodenext. Did you mean ./App.js?

**Comment by szymmis** [comment]
Hi @borzaka, thanks a lot for highlighting this issue. 
[Fix](https://github.com/szymmis/vite-express/pull/106) for that has been merged has been merged and will be released shortly.
