### ISSUE TITLE
npm run start: 'NODE_ENV' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by borzaka** [szymmis/vite-express#105]
I have created a Vite Express app with create-vite-express. React + TS. I'am on Windows.

When I run `npm run start`, I get this error:
> 'NODE_ENV' is not recognized as an internal or external command, operable program or batch file.

https://github.com/szymmis/vite-express/blob/1189de884ea240bb95c60b1db4a516c381b301f2/create-vite-express/templates/react-ts/package.json#L8

My solution: install [cross-env](https://www.npmjs.com/package/cross-env):
- `npm install --save-dev cross-env`
- create a new script called `preview`, and keep `start` unchanged
- `"preview": "cross-env NODE_ENV=production tsx src/server/main.ts",`

**Comment by szymmis** [comment]
Hi @borzaka, quite a long time since you posted this issue but I wanted to thank you for pointing that out and providing solution right away! The issue was resolved in the newest version of `create-vite-express` and everything should work out of the box even on Windows.
