### ISSUE TITLE
how can create a https server with vite-express

### ISSUE THREAD

**Issue by buffet-player** [szymmis/vite-express#113]
how can create a https server with vite-express

**Comment by szymmis** [comment]
Hi @buffet-player
You can create https server as you would typically do in express and then bind vite-express to it using `bind` method described [here](https://github.com/szymmis/vite-express?tab=readme-ov-file#async-bindapp-server-callback--promisevoid).

**Comment by buffet-player** [comment]
really thanks, it works
 // Create Vite server in middleware mode
  const server = https.createServer(credentials,app).listen(port)
  ViteExpress.bind(app, server)
}
