### ISSUE TITLE
Also export getViteConfig

### ISSUE THREAD

**Issue by srguiwiz2** [szymmis/vite-express#123]
Please at the bottom of `src/main.ts` also export `getViteConfig` for the `async function getViteConfig()`.

The purpose would be to allow writing better log lines in the callback of the `listen`.  For example to construct and write the exact URL to browse to by also using the base.

This is for someone having several projects, giving them to other people to use, each with a different base.  It would help having a little more certainty and hence sanity.

Thank you for this useful module!

**Comment by szymmis** [comment]
Version 0.16.0 was just published :rocket: Thank you for your contribution @srguiwiz2!

**Comment by szymmis** [comment]
Version 0.16.0 have been just released :rocket: Thank you for your contribution @srguiwiz2!
