### ISSUE TITLE
Add a config option lessVerbose

### ISSUE THREAD

**Issue by srguiwiz** [szymmis/vite-express#127]
It is nice to see its well crafted log lines when getting to know `vite-express` and while configuring it.

When doing further work once `vite-express` is established as a useful tool, specifically when starting small servers many times during development and automation, then it becomes distracting that there are those lines.  The way we are using it, there are several log lines in sequence.

I am about to submit a pull request to allow optionally to reduce verbosity.

**Comment by szymmis** [comment]
Version `0.17.0` is now live with this change.
