### ISSUE TITLE
Passing options to `express.static`

### ISSUE THREAD

**Issue by lucasavila00** [szymmis/vite-express#133]
I would like to configure the call to `express.static`

For my use case, I forked `vite-express` to make these changes:

```ts
async function serveStatic(): Promise<RequestHandler> {
    const distPath = await getDistPath();

    if (!fs.existsSync(distPath)) {
        info(`${pc.red(`Static files at ${pc.gray(distPath)} not found!`)}`);
        info(`${pc.yellow(`Did you forget to run ${pc.bold(pc.green("vite build"))} command?`)}`);
    } else {
        info(`${pc.green(`Serving static files from ${pc.gray(distPath)}`)}`);
    }

    return express.static(distPath, {
        index: false,
        // start changes <-------------------------------------------------------------------------------
        maxAge: "1d",
        setHeaders: setCustomCacheControl,
        // end changes  <-------------------------------------------------------------------------------
    });
}
```

I created a draft MR that shows the changes I require, but passing these as Configs: https://github.com/szymmis/vite-express/pull/132

This is a duplicate of https://github.com/szymmis/vite-express/issues/17 but I hope the use case is now justified.

**Comment by szymmis** [comment]
Hi @lucasavila00. First of all, thank a lot for taking your time to open this issue!. I saw your PR and I believe we are trying to do too much for little benefit. I'm not a fan of bringing a completely new config object to setup express.static middleware when you always can use it yourself in the code. Then you will have complete control over it. I just don't want the code itself get too complicated for a specific use case. I hope that you understand my point. Let me know what you think!

**Comment by lucasavila00** [comment]
Thanks for the response.

I understand yout point.

I do think it's unfortunate that one should use nginx or cloudflare to setup the cache headers, or forking this project.

But forking it totally fine, the code of this project is readable and easy to work with :)

**Comment by szymmis** [comment]
Hi

**Comment by szymmis** [comment]
Version `0.17.0` is now live with this change.

**Comment by lucasavila00** [comment]
Amazing!

I'm sorry for the misunderstanding.

Thank you!
