### ISSUE TITLE
Not able to install using npm or yarn

### ISSUE THREAD

**Issue by aloifran** [szymmis/vite-express#15]
After creating an app with [create-vite](https://vitejs.dev/guide/#scaffolding-your-first-vite-project) I am not able to install this package by either yarn or npm (I've updated to the latest npm and yarn)
This is the error I am getting:
`error myPath/node_modules/vite-express: Command failed.
Exit code: 2
Command: cd create-vite-express && yarn install
Arguments:
Directory: myPath/node_modules/vite-express
Output:
/bin/sh: 1: cd: can't cd to create-vite-express`

Could you please verify if this is an issue?
I have tried creating projects with create-vite templates with vue for js and ts

**Comment by codxum** [comment]
Getting the same error

**Comment by szymmis** [comment]
I verified it and there is a problem with internal postinstall script in vite-express package.json. Im quite supprised that it is run even when installed as a dependency. As far as I'm concerned you can ignore this error as it the script is run after the install and does not affect the installation process, but it will occur every time you run `yarn add` or `npm install`. A better fix would be to delete the postinstall script in vite-express package.json but it is not worth the hussle i guess as i'll post the fix as quick as possible. Thanks a lot for letting me know about the issue!

**Comment by aloifran** [comment]
Thanks for your quick reply! As far as I see this is not just an error message that I can ignore. It affects the installation because in the end no files are changed at all.

**Comment by szymmis** [comment]
Should be fixed in vite-express v0.3.3

**Comment by aloifran** [comment]
Thanks a lot!
