### ISSUE TITLE
Type Error when trying to use ES6 transpiled middleware

### ISSUE THREAD

**Issue by eko2one** [szymmis/vite-express#29]
I am having this type error and wondered if you may help out since I do not understand the problem. It may have to do with the installation requirements of the expresse package:

`Node.js 5+ because ExpreSSE is transpiled down to ES 6 ;`

Check the issue here:
https://github.com/toverux/expresse/issues/9

**Comment by Richard-So** [comment]
which version of node are you using?

**Comment by szymmis** [comment]
Hi @eko2one, could you maybe provide some more info, or maybe even some piece of code to reproduce the problem? Then I'd be happy to help you solve it!

**Comment by szymmis** [comment]
Closing as two weeks have passed without any additional info. Feel free to continue commenting on this issue if anything new comes.
