### ISSUE TITLE
How to properly configure multiple pages with vite-express?

### ISSUE THREAD

**Issue by jackblk** [szymmis/vite-express#39]
Hi there, nice project :). I'm exploring the option to properly setup Vite with Express but I'm having an issue with the `yarn dev`

I'm able to setup multiple pages/entrypoints with Vite, but I'm not able to see those pages via `vite-express` unless I specify `index.html`. If I go to viteDevServer (which is port 3001 in my case), I can see those pages just fine.

I have no issue when using prod mode (`yarn build && yarn start`).

For example, what works on prod mode:

|  | Prod | Dev |
|--------|--------|--------|
| http://localhost:3000 | ✅ | ❌ |
| http://localhost:3000/index.html | ✅ | ✅ |
| http://localhost:3000/route1/ | ✅ | ❌ |
| http://localhost:3000/route1/index.html | ✅ | ✅ | 

Any idea on how I can fix this?

-----

Here's my folder structure:

```
├── package.json
├── vite.config.js
├── src
│   ├── frontend
│   │   ├── index.html
│   │   ├── main.js
│   │   ├── route1
│   │   │   ├── index.html
│   │   backend
│   │   ├── main.js
```

My `package.json` scripts:

```json
    "dev": "nodemon src/backend/main.js -w src/backend | pino-pretty",
    "start": "NODE_ENV=production node src/backend/main.js",
    "build": "vite build"
```

Here's my `src/backend/main.js`:

```javascript
const port = 3000;
ViteExpress.config({
  vitePort: 3001,
  printViteDevServerHost: true,
});
ViteExpress.listen(app, port, () => console.log(`Server running at http://${os.hostname()}:${port}`));
```

My `vite.config.js`:

```javascript
import react from "@vitejs/plugin-react";
import { defineConfig } from "vite";
import path from "path";
import { fileURLToPath } from "url";

const dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(dirname, "src", "frontend");
const outDir = path.join(dirname, "dist");

export default defineConfig({
  root,
  plugins: [react()],
  build: {
    outDir,
    rollupOptions: {
      input: {
        main: path.join(root, "index.html"),
        route1": path.join(root, "route1", "index.html"),
      },
    },
  },
});
```

**Comment by szymmis** [comment]
Hi @jackblk, thanks a lot for openning this issue. As you can see it was already resolved, as it was quite small change. For details you can look into #42.

I'll ship the change in the next patch version.
