### ISSUE TITLE
Why not Vite Middleware Mode

### ISSUE THREAD

**Issue by 6XGate** [szymmis/vite-express#48]
I was checking out the docs to Vite's SSR support and discovered Vite has a middleware mode that can be hooked right into express. I was wondering why not use that rather than the discrete vite dev server. It will still work with client-side rendering as long as your framework's SSR mode is not enabled.

https://vitejs.dev/guide/ssr.html#setting-up-the-dev-server

**Comment by szymmis** [comment]
Hi @6XGate. I don't know what exactly are you asking about. My answer is that `vite-express` works just like that example from the docs you linked.The only difference is that it doesn't run Vite Dev Server in middleware mode and doesn't use `vite.middleware`. I see a possibility for some refactor to use that functionalities internally, but the overall effect would be still the same, just using a little more code from Vite and less custom code.

I don't know if that answers your question, feel free to let me know if not, and I'll try to answer the best I can.

**Comment by 6XGate** [comment]
This is probably more of a feature request than a question. It seems using the Middleware Mode would side step the need to run a separate server for the Vite HMR. I tried it using this project as an example of the Express.js setup and just called the Vite middlewares where you forwarded to the Vite server. I can share that code if need be to see.

**Comment by szymmis** [comment]
Yeah sure. If you have some code that I can take a look at, that would be super useful for me to understand the details here.

**Comment by szymmis** [comment]
Okay, I've got some time to look into the docs once again and I want to say that I was wrong, sorry about that.

You are absolutely right that we would be able to ditch Vite Dev Server instance by using this middleware mode. That's quite exciting because it will be possible to remove a lot of moving parts for more stable solutions. I'll try to experiment with it as soon as I'll have some more time.

Thanks a lot @6XGate for pointing that out and I want to apologize again for my misunderstanding.

**Comment by 6XGate** [comment]
Here is a gist I created [Combining Express JS and Vite Dev Server](https://gist.github.com/6XGate/cd58d6f1f70d2aa98555595c0e46ade9)

**Comment by szymmis** [comment]
Okay, so as you can see I've created a PR with the changes and merged it, so if you are interested in how I handled it you can check it out. As I said I've managed to replace a lot of code with something more stable in my opinion.

Thanks a lot @6XGate for your suggestion, and sorry again for misjudging your comment at first.
