### ISSUE TITLE
how to do file routing?

### ISSUE THREAD

**Issue by grfd9** [szymmis/vite-express#69]
Is it possible to do file routing (e.g vite-plugin-ssr), how can I do it?

**Comment by szymmis** [comment]
Hi @grfd9, it is not currently possible to easily achieve file routing. `vite-express` isn't designed to be used alongside `vite-plugin-ssr`. You would need to have some kind of Vite plugin that does that for you, but not as big in terms of functionality as `vite-plugin-ssr` so it doesn't interfere with the `vite-express`.

**Comment by angelhdzmultimedia** [comment]
> Is it possible to do file routing (e.g vite-plugin-ssr), how can I do it?

Maybe what you need is Nuxt? https://nuxt.com/
