### ISSUE TITLE
Checking wrong dist path for build in production

### ISSUE THREAD

**Issue by vincesp** [szymmis/vite-express#7]
In production, the correct path is used for hosting static files. However, when checking whether to build the files, the wrong path is used:
https://github.com/szymmis/vite-express/blob/master/src/main.ts#L42

This means when `config.root` is configured then we will rebuild on every launch.

**Comment by szymmis** [comment]
Hi @vincesp.
That's a great catch, definitely slipped by. 
Thanks for that!
I'll ship it in the next patch release v0.3.1
