### ISSUE TITLE
Getting 404-Error after deployment

### ISSUE THREAD

**Issue by julix14** [szymmis/vite-express#71]
Hi there,
i was very satisfied while working with vite-express during the development. Now i want to deploy my application on Vercel. This worked quiet well with one exception.
The problem is that i am getting a 404-Error on my API Route defined in my `server/main.js`:
It looks like this:
```
const express = require("express");
const ViteExpress = require("vite-express");

const app = express();

app.get("/hello", (req, res) => {
    res.send("Hello Vite + Vue!");
});

ViteExpress.listen(app, 3000, () =>
    console.log("Server is listening on port 3000...")
);
```
Maybe i missed some configuration in the readme-file, but i'm quite new to this topic and maybe i didn't searched for the right "keywords".

**Comment by szymmis** [comment]
Hi @julix14, I believe that it isn't possible to host an express app on Vercel because they are based on serverless approach. You need something that will be able to host an express instance as a server not a lambda function handler. 
I haven't use it but maybe https://www.cyclic.sh/ will do? It seems that they have a free tier.

**Comment by julix14** [comment]
Hi @szymmis,
first thanks for your help. I tried running it there and the Express Server is running, but now i get the "Cannot /GET" Error, when i want to try to reach my Vue-Routes.
Do i have an Thinking error when i try do deploy everything (Express & Vue) with the same service and i need to deploy it into different services?
Or do i have to make any Configurations next to the `ViteExpress.config({ mode: "production" });`?

Thanks in advance for your help!

**Comment by szymmis** [comment]
I guess that you didn't built your app with `yarn build`/`npm run build` command when deploying it, so there are no static files to serve. Using express and vite in one app is 100% use case for `vite-express` so what you are trying to do is absolutelty correct. Let me know if that information helps.

**Comment by julix14** [comment]
Hi, sorry for the late response. Now i finally got it to run. I built it correctly, but missed it to check the "Serve output as static" option. After checking this option everything works. Thanks very much for your help and for building this repo. It carries me through my university projects and the dev-Experience is very good! ❤️
