### ISSUE TITLE
configuring handlebars for production

### ISSUE THREAD

**Issue by mnkcoder** [szymmis/vite-express#76]
I am trying to achieve following:

- My site doesn't require react for landing pages such as home page, about, FAQs etc. So there are some routes such as **/about, /faqs** etc. where I need to render/serve these pages from express via handlebars with some vanilla JS/CSS.
- However, there are some routes in the site that warrants heavy FE work such as React.

Here is the repo where I have the sample code I am testing out with https://github.com/mnkcoder/vite-express-project

In dev mode everything is working as expected with HMR and landing page routes. But I am running into below issues while running in production mode:

Issue 1: 

**src/server/views/partials/commonScripts.html** in dev mode is this

```
{{#if isDevelopment}}

<script type="module">
  import RefreshRuntime from "http://localhost:3000/@react-refresh";
  RefreshRuntime.injectIntoGlobalHook(window);
  window.$RefreshReg$ = () => {};
  window.$RefreshSig$ = () => (type) => type;
  window.__vite_plugin_react_preamble_installed__ = true;
</script>
<script type="module" src="/@vite/client"></script>

{{/if}}

```

when I run `npm run build` the above is translated to below

```
<script type="module" crossorigin src="/assets/scripts-7a266bfa.js"></script>
<link rel="modulepreload" crossorigin href="/assets/modulepreload-polyfill-3cfb730f.js">
{{#if isDevelopment}}

{{/if}}

```

the issue here is the generated html has script and link tags outside the handlebars's  `{{#if isDevelopment}}` conditional flag

Issue 2:
 **src/server/views/home.html** in dev mode is this

```
<div id="root"></div>

<script type="module" src="/src/client/home.tsx"></script>

```
after `npm run build` the above is translated to below

```
<script type="module" crossorigin src="/assets/home-a8fd483f.js"></script>
<link rel="modulepreload" crossorigin href="/assets/client-99d9e3e1.js">
<link rel="stylesheet" href="/assets/client-e3a8f781.css">
<div id="root"></div>

```

The issue here is that its injecting script tag after the root div element.

Any suggestions here would be super helpful. Let me know if I need to provide any additional information.

**Comment by szymmis** [comment]
Hi @mnkcoder, I don't have much experience with handlebars, but it looks like it is an issue related to Vite directly, not `vite-express` itself. You could try to look for some handlebars plugins, maybe there is something that would help you.

The only thing that I can say, from what I see in your repository, is to ask if you need to specify "SSR" routes in `vite.config.js` as additional rollup inputs? I think that's the reason why those files are changed during the build step, and if I understand it correctly, express is responsible for rendering those paths using handlebars engine so Vite doesn't need to know about the at all.

If you need to preprocess those handlebars templates during the Vite build process, then maybe there is some kind of Vite's plugin you need to look for, as I suggested.

**Comment by szymmis** [comment]
Due to inactivity, I'll close this issue, feel free to continue this issue if you have any more questions.
