### ISSUE TITLE
Donation/Buy me a coffe button is missing

### ISSUE THREAD

**Issue by aldomeza-dev** [szymmis/vite-express#80]
Hi @szymmis, you should totally add a button for donattions!

_Possible services to set it up:_

[Ko-Fi](https://ko-fi.com/[)

Buy Me a Coffee](https://www.buymeacoffee.com/)

Hope this doesn't come as an insult or anything, if so please forgive me 🙏🏼

**Comment by szymmis** [comment]
Hi @aldomeza-dev, that's very nice of you to propose that, but I don't think that donations are needed based on how small this library is. There are projects out there that need the funding much more!

Nontheless, it really means a lot to me that you think this project is donation-worthy, thanks!
