### ISSUE TITLE
"vite failed to connect to websocket", "vitejs/plugin-react can't detect preamble"

### ISSUE THREAD

**Issue by alexjshaw** [szymmis/vite-express#81]
I'm hoping you might be able to help out with this issue I'm having.

When I first set up a new app using "npm create vite-express" and ran the server it was loading fine, I could get to localhost:3000 on every browser. I built a few routes, connected it up to mongodb and added in auth0 JWT handling, and all of that stuff is working fine, but now when I go to localhost:3000 on any browser it loads the title and icon but none of the react.

The main errors I get are:

Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-8ZgGo/nOlaDknQkDUYiedLuFRSGJwIz6LAzsOrNxhmU='), or a nonce ('nonce-...') is required to enable inline execution.

Refused to connect to 'ws://localhost:24678/' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'connect-src' was not explicitly set, so 'default-src' is used as a fallback.
setupWebSocket | @ | client.ts:77
  | (anonymous) | @ | client.ts:67

App.jsx:12 Uncaught Error: @vitejs/plugin-react can't detect preamble. Something is wrong. See https://github.com/vitejs/vite-plugin-react/pull/11#discussion_r430879201
    at App.jsx:12:11
(anonymous) @ App.jsx:12

I've been bashing my head against this for ages and can't figure it out, is there any chance you can spot what's wrong?

Thanks.

The full code for my server.js file is:

`import express from 'express'
import ViteExpress from 'vite-express'
import cors from 'cors'
import helmet from 'helmet'
import morgan from 'morgan'
import './database/mongo.js'
import { insertAd, getAds, deleteAd, updateAd } from './database/ads.js'
import { auth } from 'express-oauth2-jwt-bearer'

const app = express()

const jwtCheck = auth({
  audience: 'https://archery-app-api',
  issuerBaseURL: 'https://dev-wn87thdr6glngf33.uk.auth0.com/',
  tokenSigningAlg: 'RS256'
})

app.use(express.json())
app.use(helmet())
app.use(cors())
app.use(morgan('combined'))

app.get('/ads', jwtCheck, async (req, res) => {
  const ads = await getAds()
  res.json({ status: 'success', data: ads })
})

app.post('/ads', jwtCheck, async (req, res) => {
  const newAdData = req.body
  const newAd = await insertAd(newAdData)
  res.json({ status: 'New ad inserted', data: newAd })
})

app.delete('/ads/:id', jwtCheck, async (req, res) => {
  const deletedAdId = req.params.id
  const deletedAd = await deleteAd(deletedAdId)
  res.json({ status: 'Ad deleted', data: deletedAd })
})

app.put('/ads/:id', jwtCheck, async (req, res) => {
  const updatedAdData = req.body
  const updatedAdId = req.params.id
  const updatedAd = await updateAd(updatedAdId, updatedAdData)
  res.json({ status: 'Ad updated', data: updatedAd })
})

app.get('/hello', (req, res) => {
  res.send('Hello Vite + React!')
})

// Error Catch Middleware
app.use((err, req, res, next) => {
  console.error(err.stack)
  res.status(500).send('Something broke!')
})

ViteExpress.listen(app, 3000, () =>
  console.log('Server is listening on port 3000...')
)
`

**Comment by szymmis** [comment]
Hi @alexjshaw, from a quick look at the code, the only thing on top of my head that you might be missing is [this](https://github.com/szymmis/vite-express#static--requesthandler). 
Maybe static files are blocked by your authentication, so try to address that with `ViteExpress.static()`.
If that doesn't work, try to commend out the code piece by piece up to the moment when everything work.
Let me know if that helps anyhow.

**Comment by szymmis** [comment]
Glad to hear that you managed to resolve the issue. Also really cool that the transformer function did come handy. Where do you found the solution if I might ask?

Also, one small thing: 
If you want to attach a code block use three backticks **`** instead of one.
Like that: ```javascript and end it with three backtics again.

**Comment by aldomeza-dev** [comment]
> ViteExpress.config({ transformer: transformIndexHtml })`

Having the same Issue but this wont fix it, any thoughts?

```javascript
// main.js

const fs = require('fs')
const chalk = require('chalk')
const express = require('express')
const ViteExpress = require('vite-express')
const session = require('express-session')
const MemoryStore = require('memorystore')(session)
const { v4: uuidv4 } = require('uuid')
const bodyparser = require('body-parser')
const Datastore = require('@seald-io/nedb')
const webPush = require('web-push')
const https = require('https')
const morgan = require('morgan')
const cors = require('cors')
const hpp = require('hpp')
const helmet = require('helmet')
const crypto = require('crypto')

require('dotenv').config({ path: 'src/config/.env' })

// Create a NeDB database
const db = new Datastore({
  filename: 'src/database/aaaaa.db',
  autoload: true,
})

webPush.setVapidDetails(
  'mailto:aaaa@aaa.aa',
  process.env.VITE_PUBLIC_VAPID_KEY,
  process.env.PRIVATE_VAPID_KEY
)


const app = express()

app.use(
  session({
    secret: uuidv4(),
    store: new MemoryStore({
      checkPeriod: 86400000,
    }),
    resave: false,
    saveUninitialized: true,
    name: 'aaaaa',
    cookie: {
      maxAge: 8 * 60 * 60 * 1000,
      sameSite: 'strict',
    },
  })
)

const { sessionChecker } = require('./middlewares/auth.js')

const alert = require('./routes/alertsRoutes.js')
const notification = require('./controllers/notifications.js')
const task = require('./controllers/tasks.js')
const dashboard = require('./controllers/dashboard.js')
const graph = require('./controllers/graph.js')
const login = require('./controllers/login.js')
const logout = require('./controllers/logout.js')

const ping = require('./controllers/ping')

/* 
! CONFIGURATION 
*/
app.use(express.json())
app.use(express.urlencoded({ extended: false }))
app.use(morgan('dev'))
app.use((req, res, next) => {
  req.cspNonce = crypto.randomBytes(16).toString('hex')
  next()
})

/* 
! SECURITY 
*/
app.use(cors())
app.use(hpp())
// Allow CSP for Vite
app.use(
  helmet({
    contentSecurityPolicy: {
      directives: {
        'script-src': ["'self'", (req, res) => `nonce-${req.cspNonce}`],
      },
    },
  })
)
app.disable('x-powered-by')

function transformIndexHtml(html, req, res) {
  const regex = /<script(.*?)/gi
  const replacement = `<script nonce="${req.cspNonce}"`
  console.log(replacement)
  return html.replace(regex, replacement)
}

app.use('/v1/login', login)
app.use('/v1/logout', logout)
app.use('/v1/alerts', sessionChecker, alert)
app.use('/v1/notifications', notification)
app.use('/v1/tasks', sessionChecker, task)
app.use('/v1/dashboard', sessionChecker, dashboard)
app.use('/v1/graphs', sessionChecker, graph)

app.use('/v1/ping', ping)

const PORT = process.env.EXPRESS_PORT || 3000

if (process.env.USE_SSL == 'true') {
  const sslOptions = {
    key: fs.readFileSync(process.env.SSL_KEY_PATH),
    cert: fs.readFileSync(process.env.SSL_CERT_PATH),
  }

  const server = https.createServer(sslOptions, app).listen(PORT, () => {
    console.log(
      chalk.red.bold('HTTPS server ') +
        chalk.green('is listening on port ') +
        chalk.yellow(`${process.env.aaaaa}`)
    )
  })

  ViteExpress.bind(app, server)
  ViteExpress.config({
    mode: process.env.NODE_ENV,
    // ignorePaths: '/v1',
    transformer: transformIndexHtml,
  })
} else {
  ViteExpress.listen(app, process.env.EXPRESS_PORT, () => {
    console.log(
      chalk.blue.bold('HTTP server ') +
        chalk.green('is listening on port') +
        chalk.yellow(`${process.env.aaaa}`)
    )
  })

  // ViteExpress.config({
  //   mode: process.env.NODE_ENV,
  //   ignorePaths: ['/v1'],
  //   transformer: transformIndexHtml,
  // })
}


```
