### ISSUE TITLE
Entire project directory exposed in development mode

### ISSUE THREAD

**Issue by Rigidity** [szymmis/vite-express#82]
When running an `express` application using `vite-express` in `NODE_ENV=development` (which is the default), all local files are statically exposed. You have to explicitly set `NODE_ENV=production`, or you can risk leaking secrets, configuration files, Git repository credentials, and source code.

I'm not sure what use-case there is for exposing everything in the root project directory in development mode is. Only the public folder should be exposed regardless, in order to prevent things like this from happening.

This unexpected behavior resulted in a security issue for a project I maintain.

**Comment by Rigidity** [comment]
While yes, it is a mistake to not set the `NODE_ENV` correctly and to not use a dockerignore file to hide sensitive files, this is something that should be trivial to prevent from the webserver side as well, by not exposing the entire local dir as static files.

I can imagine this could cause more than security concerns, such as conflicting files in your public folder and your root dir, or static files conflicting with routes in single page applications.

**Comment by szymmis** [comment]
Hi @Rigidity.
This behaviour comes from the `Vite` itself. `vite-express` is just a thin layer that connects `express` with `Vite` and I have not altered this behaviour at all. It is just how development mode works in Vite. You shouldn't run your server in development mode as described in [🚚 Shipping to production](https://github.com/szymmis/vite-express#-shipping-to-production) section.

As soon as you build your frontend and run your server in production mode, only files that are served are from your `dist` directory, and form whatever logic that you write on express.

I won't be making any code changes related to that issue, as I believe that everything is working as intended.
