### ISSUE TITLE
Bun support?

### ISSUE THREAD

**Issue by BryceBlankinship** [szymmis/vite-express#85]
With bun v1.0 officially out, do you plan to add a bun support option? Maybe the plugin auto-configures based on how it was invoked (if thats possible)... I can try to make the PR if you want.

**Comment by szymmis** [comment]
Hi, sorry for such late response. I don't think there is anything to do in regards to bun support. `vite-express` can be used with it out of the box, just as in node (at least default template generated by `bun create vite-express` is working just fine.

If you have any idea how would that integration look like or work, I'd be happy to listen and also accept any kind of PR!

**Comment by BryceBlankinship** [comment]
I ran into some sort of issue but can't remember what it was. I'll try to find it again sometime. Will close this for now.

**Comment by szymmis** [comment]
Sure thing! As soon as something will pop up let me know. I promise, I won't take that much time to respond next time 😅
