### ISSUE TITLE
Multiple entry points for multi page app

### ISSUE THREAD

**Issue by mdchad** [szymmis/vite-express#87]
Hi @szymmis, firstly thanks for creating this great library. I just started using it and created my project using the create-vite-express. My question is how can i add multiple entry points. One i'm using it for my landing page and the other for my dashboard. 

this is my file structure. I'm following what is on Vite documentation and added index.html inside the app folder. [Vite docs](https://vitejs.dev/guide/build.html#multi-page-app)

![Screenshot 2023-10-25 at 3 57 23 PM](https://github.com/szymmis/vite-express/assets/2016750/c31696b7-cd93-43cf-bcc6-dfb9e9517600)

and here is my config:

```
import { defineConfig } from "vite";
import { resolve } from 'path'
import react from "@vitejs/plugin-react";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
  rollupOptions: {
    input: {
      landing: resolve(__dirname, 'index.html'),
      app: resolve(__dirname, 'src/app/index.html')
    }
  }
});
```

How can i go about this. Any input is greatly appreciated!

**Comment by szymmis** [comment]
Hi @mdchad, as far as I'm concerned, this feature (multiple HTML entries) is currently not supported in `vite-express`. I know that there were some complications related to that, and I had to abandon this feature. I'll check what can I do to support it. Just need some time to take a look at it. Thanks a lot for raising this issue!

**Comment by elturpin** [comment]
@mdchad 
If you want the new behavior brought by my PR, I created a new branch where the npm `prepare` script build the package.

You can then do `npm install elturpin/vite-express#npm-install` and it should work.

Tel me if you think it suits your needs.

**Comment by szymmis** [comment]
Thanks to @elturpin, this feature is supported in v0.11.0! :tada:
