### ISSUE TITLE
Reload server.ts

### ISSUE THREAD

**Issue by malikiz** [szymmis/vite-express#90]
Hi, I can't figure out how to reload my application when editing `server.ts`, how can I achieve this?

In my case I want to edit the example:
```tsx
app.get("/message", (_, res) => {
    res.send("Hello from express!")
});
```
When I edit `server.ts` nothing happens. `F5` key in browser does not help me. For this I have to restart the application manually

**Comment by szymmis** [comment]
Hi @malikiz, every change in server-side code needs an application restart. 
If you want to have it automated on file save you can use [`nodemon`](https://www.npmjs.com/package/nodemon). That's a package that create-vite-express templates use. Check out [this](https://github.com/szymmis/vite-express/blob/master/create-vite-express/templates/react/package.json) package.json for an example.

**Comment by malikiz** [comment]
Thanks for the hint, it really works. Just in case, I'll write how to implement this on node 20 and typescript 5 versions:

in `package.json`:
```json
{
  "type": "module",
  "scripts": {
      "dev": "nodemon --exec \"node --loader ts-node/esm\" ./src/server/server.ts -w ./src/server"
  }
}
```
in `tsconfig.json`:
```json:
{
  "ts-node": {
    "transpileOnly": true,
  }
}
```

**Comment by malikiz** [comment]
I'm closing this issue
