### ISSUE TITLE
Update nodemon SemVer to ^3.0.0

### ISSUE THREAD

**Issue by pontusva** [szymmis/vite-express#93]
Tried it and everything seems to work with the updated nodemon version.

**Comment by szymmis** [comment]
Hi @pontusva, thanks for letting me know. I guess you are talking about `create-vite-express` templates, yeah, their dependencies are a little bit outdated so I'll try to update them.

**Comment by pontusva** [comment]
@szymmis Hey! 
Yes, that was what i was referring to. I think i got the repos mixed up? 


> Hi @pontusva, thanks for letting me know. I guess you are talking about `create-vite-express` templates, yeah, their dependencies are a little bit outdated so I'll try to update them.

**Comment by szymmis** [comment]
No no, you got the repo right. The `create-vite-express` is a subpackage of this repo.

Maybe you want to make a contribution and update the dependencies? If you do, I'll be happy to answer any questions you'll have and provide guidance! If not then no problem and as I said, I'll try to find some free time to update them.
Either way, thanks again for letting me know!

**Comment by pontusva** [comment]
> No no, you got the repo right. The `create-vite-express` is a subpackage of this repo.
> 
> Maybe you want to make a contribution and update the dependencies? If you do, I'll be happy to answer any questions you'll have and provide guidance! If not then no problem and as I said, I'll try to find some free time to update them. Either way, thanks again for letting me know!

Oh okay, thank you for letting me know :)
I'd really  like to contribute and update the dependencies. I would be my first contribution and this seems like a good one to start with. 

Is there a specific workflow for contributing?

**Comment by szymmis** [comment]
Happy to hear that!

There is no official guideline at the moment. That means all you have to do is to:
1. fork the repository
2. make changes on your fork
3. create a PR onto this repository. 

As soon as the PR shows up I'll try to check it out, and we can discuss details there.

In terms of requirements: I'd like you to update every dependency you can in every template. 
You can run `npm run test` to check out if your changes work. I know that there are problems with tests on Windows. In that case you can simply create a local project and check it there manually. Whatever workflow suits you.

And as I said earlier, when you are ready, just open the PR.
Feel free to ask if anything is still unclear.

**Comment by pontusva** [comment]
Ok, I'll look into this :) and reply here if i have any further questions

**Comment by pontusva** [comment]
Hey @szymmis 

I'm a bit new to forking and contributing in general. But i've made a fork and updated all dependecies. All tests passed. But i noticed this: https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated 

And also i pushed to  branch on the fork i made but it seems that it is connected to this repo? Maybe that¨s normal behaviour :)

**Comment by szymmis** [comment]
Okay, that link looks interesting, definitely something I need to check out.
Are you getting some kind of warnings or how did you stumbled upon this?

Yeah, your fork is connected to this repository, that's how they work. It's different from just creating a new repository on your account and pasting all the files there. Forks are generally used as a way to implement some changes to public repositories that you don't have write access as this one. It is de facto a standard of contributing.
You can open a PR now merging your branch onto this one.
That way I'll be able to check it out and test myself.
